users
    id
    user_name
    email
    password
    status(active/unverified/ban)
    role
    token
    joined_date
    refresh_token
    telephone
    address
    timestamp

categories
    id
    category_name
    category_url
    slug


products
    id
    product_name
    category (product can able in multiple category)
    price
    description
    variants
    attributes
    images

orders
    increment_id
    customer_id
    items_purchased
    created_at
    