import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";

import "./styles/globals.css";

export const metadata = {
  title: "Create Next Web App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<React.PropsWithChildren>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
      </body>
    </html>
  );
}
